name: discord-bot

services:
  discord-bot-container:
    build: .
    restart: unless-stopped
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_HOST
      - MYSQL_DB
      - DISCORD_TOKEN
    networks:
      - shared-network


networks:
  shared-network:
    name: shared-network
  
