"""add_soundboard_table

Revision ID: 3f614f1a70b6
Revises: efd724fcb72c
Create Date: 2026-09-12 23:38:44.377116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f614f1a70b6'
down_revision: Union[str, Sequence[str], None] = 'efd724fcb72c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soundboard',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uploader', sa.BigInteger(), nullable=False),
    sa.Column('uploader_name', sa.String(length=150), nullable=False),
    sa.Column('local_file_name', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('times_played', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soundboard_name'), 'soundboard', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_soundboard_name'), table_name='soundboard')
    op.drop_table('soundboard')
    # ### end Alembic commands ###
