"""added vaults for storing points

Revision ID: efd724fcb72c
Revises: 212e121ebb02
Create Date: 2026-09-05 22:14:36.215428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efd724fcb72c'
down_revision: Union[str, Sequence[str], None] = '212e121ebb02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point_vaults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vault_name', sa.String(length=150), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vault_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('point_vaults')
    # ### end Alembic commands ###
