name: discord-bot-builder

on:
  push:
    branches: [main]

env:
  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
  MYSQL_USER: ${{ secrets.MYSQL_USER }}
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
  MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
  MYSQL_DB: ${{ secrets.MYSQL_DB }}

jobs:
  container-builder:
    runs-on: self-hosted
    steps:
      - name: checkout repository
        uses: actions/checkout@v6

      - name: Stop delete containers
        run: docker compose down

      - name: Start Containers
        run: docker compose up -d --build